version: 0.0
os: linux
files:
  - source: /
    destination: /home/release
hooks:
  BeforeInstall:
    - location: CodeDeploy/remove_resources
      timeout: 300
      runas: root
  ApplicationStart:
    - location: CodeDeploy/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: CodeDeploy/stop_server
      timeout: 300
      runas: root
